import { getAllColoringImages, getColoringImage } from '@/app/actions';
import ColoringImage from '@/components/ColoringImage/ColoringImage';
import PageWrap from '@/components/PageWrap/PageWrap';

type ColoringImagePageProps = {
  params: {
    id: string;
  };
};

export const generateStaticParams = async () => {
  const images = await getAllColoringImages();

  return images.map((image) => ({
    params: {
      id: image.id,
    },
  }));
};

export const generateMetadata = async ({
  params: { id },
}: ColoringImagePageProps) => {
  const coloringImage = await getColoringImage(id);

  if (!coloringImage) {
    return null;
  }

  const title = `${coloringImage.title} - Chunky Crayon`;
  const description =
    `A coloring image featuring: ${coloringImage.description}` ||
    'Coloring book page generated by Chunky Crayon.';
  const keywords =
    coloringImage.tags?.join(',') ||
    'coloring book, AI art, generative art, coloring pages, digital coloring, creative app';

  return {
    title,
    description,
    keywords,
    icons: {
      icon: '/favicon.ico',
      shortcut: '/favicon-16x16.png',
      apple: '/apple-touch-icon.png',
    },
    openGraph: {
      title,
      description,
      url: 'https://chunkycrayon.com',
      siteName: 'Chunky Crayon',
      images: [
        {
          url: coloringImage.url || 'https://chunkycrayon.com/og-image.jpg',
          width: 1200,
          height: 630,
          alt:
            coloringImage.alt ||
            'Chunky Crayon AI-Generated Coloring Book Pages',
        },
      ],
      locale: 'en-GB',
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [coloringImage.url || 'https://chunkycrayon.com/og-image.jpg'],
    },
  };
};

const ColoringImagePage = async ({
  params: { id },
}: ColoringImagePageProps) => {
  const coloringImage = await getColoringImage(id);

  if (!coloringImage) {
    return null;
  }

  return (
    <PageWrap className='bg-gradient-to-br from-[#FFF2E6] to-[#FFE6CC]" justify-center items-center gap-y-32'>
      <div className="max-w-3xl w-full p-8 bg-[#FF8A65] rounded-lg shadow-lg">
        <div className="flex flex-col items-center text-center mb-8">
          <h1 className="font-dyna-puff text-5xl font-bold mb-2 text-white">
            {coloringImage.title}
          </h1>
          <div className="flex items-center gap-x-2 text-lg text-white font-mediu">
            by Chunky Crayon
          </div>
        </div>
        <ColoringImage
          id={id}
          showActions
          className="rounded-lg shadow-lg bg-white"
        />
      </div>
    </PageWrap>
  );
};

export default ColoringImagePage;
