import { getAllColoringImagesStatic, getColoringImage } from '@/app/actions';
import ColorPalette from '@/components/ColorPalette/ColorPalette';
import ImageCanvas from '@/components/ImageCanvas/ImageCanvas';
import PageWrap from '@/components/PageWrap/PageWrap';
import DownloadPDFButton from '@/components/buttons/DownloadPDFButton/DownloadPDFButton';

type ColoringImagePageProps = {
  params: Promise<{
    id: string;
  }>;
};

// eslint-disable-next-line @typescript-eslint/naming-convention
export const experimental_ppr = true;

export const generateStaticParams = async () => {
  const images = await getAllColoringImagesStatic();

  return images.map((image) => ({
    params: {
      id: image.id,
    },
  }));
};

// revalidate every hour
export const revalidate = 3600;

export const generateMetadata = async (props: ColoringImagePageProps) => {
  const params = await props.params;
  const { id } = params;
  const coloringImage = await getColoringImage(id);

  if (!coloringImage) {
    return null;
  }

  const title = `${coloringImage.title} - Chunky Crayon`;
  const description =
    `A colouring image featuring: ${coloringImage.description}` ||
    'Colouring book page generated by Chunky Crayon.';
  const keywords =
    coloringImage.tags?.join(',') ||
    'colouring book pages, creative app for kids, personalized colouring pages, educational worksheets, fun learning activities, kids creativity app, interactive colouring app, digital colouring, printable colouring pages, connect the dots, hangman, kids educational games, math worksheets, English worksheets, kids learning tools, creative learning, kids drawing activities, home learning, school learning, web app for kids, iOS app for kids, Android app for kids, Chunky Crayon, fun educational app';

  return {
    title,
    description,
    keywords,
    icons: {
      icon: '/favicon.ico',
      shortcut: '/favicon-16x16.png',
      apple: '/apple-touch-icon.png',
    },
    openGraph: {
      title,
      description,
      url: 'https://chunkycrayon.com',
      siteName: 'Chunky Crayon',
      images: [
        {
          url:
            coloringImage.url || 'https://chunkycrayon.com/images/og-image.jpg',
          width: 1200,
          height: 630,
          alt:
            coloringImage.alt ||
            'Chunky Crayon AI-Generated Colouring Book Pages',
        },
      ],
      locale: 'en-GB',
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [
        coloringImage.url || 'https://chunkycrayon.com/images/og-image.jpg',
      ],
    },
  };
};

const ColoringImagePage = async (props: ColoringImagePageProps) => {
  const { params } = props;
  const { id } = await params;

  const coloringImage = await getColoringImage(id);

  if (!coloringImage) {
    return null;
  }

  return (
    <PageWrap className='bg-gradient-to-br from-[#FFF2E6] to-[#FFE6CC]" justify-center items-center gap-y-32'>
      <div className="max-w-3xl w-full p-8 bg-[#FF8A65] rounded-lg shadow-lg">
        <div className="flex flex-col items-center text-center mb-8">
          <h1 className="font-dyna-puff text-5xl font-bold mb-2 text-white">
            {coloringImage.title}
          </h1>
          <div className="flex items-center gap-x-2 text-lg text-white font-mediu">
            by Chunky Crayon
          </div>
        </div>
        <div className="flex flex-col gap-y-4">
          <ColorPalette className="self-center" />
          <ImageCanvas
            coloringImage={coloringImage}
            className="rounded-lg shadow-lg bg-white overflow-hidden"
          />
          <DownloadPDFButton
            coloringImage={coloringImage}
            className="self-center"
          />
        </div>
      </div>
    </PageWrap>
  );
};

export default ColoringImagePage;
